# Generated by Django 3.2 on 2022-05-18 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e12d8340-bdd6-46f3-b9ba-5d3d72b80138')),
        ),
    ]
