# Generated by Django 3.2 on 2022-05-18 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b3cc6388-c2dd-406d-8daf-c1aadfd88874')),
        ),
    ]
