# Generated by Django 3.2 on 2022-05-18 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b5bfcf4d-4ede-4846-9e71-2881c05757f0')),
        ),
    ]
