# Generated by Django 3.2 on 2022-05-18 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e5c7105e-bb77-4166-8ca4-c8dc6ecdc28c')),
        ),
    ]
