# Generated by Django 3.2 on 2022-05-18 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e3f1bda6-c190-4f3e-a331-f2696cf0f910')),
        ),
    ]
