# Generated by Django 3.2 on 2022-05-19 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('090a1315-d43b-4c9c-bb7a-2b7d425677d2')),
        ),
    ]
