# Generated by Django 3.2 on 2022-05-19 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('253ec8c7-2387-4190-adba-9e75871d6e85')),
        ),
    ]
