# Generated by Django 3.2 on 2022-05-19 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0017_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c7c0409b-fe94-4da3-9ecc-68ddef59ca3c')),
        ),
    ]
