# Generated by Django 3.2 on 2022-05-19 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0019_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2307734f-101b-4cf6-b088-64039ee6526c')),
        ),
    ]
